-- ============================================================
-- SEED POP — Template Mestre (252 atividades / 12 módulos), Overlay
-- Brasília (31), 15 gates, 11 fornecedores. Idempotente.
-- ============================================================

INSERT INTO public.venues (name, city, state) SELECT 'Centro de Convenções Ulysses Guimarães', 'Brasília', 'DF' WHERE NOT EXISTS (SELECT 1 FROM public.venues WHERE name = 'Centro de Convenções Ulysses Guimarães');

INSERT INTO public.templates (name, event_type, description, template_kind, version, status)
SELECT 'Congresso Science Play · POP Mestre', 'congresso', 'POP Mestre com os 12 módulos estruturais de um congresso Science Play.', 'master', 1, 'publicado'
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre');

INSERT INTO public.templates (name, event_type, description, template_kind, parent_template_id, venue_id, version, status)
SELECT 'Nutrição Brasil Brasília · Ulysses Guimarães', 'congresso', 'Overlay da edição Brasília: regras, fornecedores e atividades específicas do Ulysses Guimarães.', 'overlay',
  (SELECT id FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre'),
  (SELECT id FROM public.venues WHERE name = 'Centro de Convenções Ulysses Guimarães'), 1, 'publicado'
WHERE NOT EXISTS (SELECT 1 FROM public.templates WHERE name = 'Nutrição Brasil Brasília · Ulysses Guimarães');

INSERT INTO public.pop_modules (template_id, module_key, name, objective, sort_order)
SELECT t.id, m.mk, m.name, m.obj, m.so
FROM (VALUES
 ('m01_estrategia','Planejamento Estratégico','Definir toda a estrutura estratégica do congresso antes do início da comercialização.',1),
 ('m02_local','Local do Evento e Infraestrutura','Garantir a contratação e preparação da infraestrutura física do evento.',2),
 ('m03_comercial','Comercial, Patrocínio e Feira','Gerenciar toda a operação comercial e a área de exposição do congresso.',3),
 ('m04_marketing','Marketing e Comunicação','Planejar e executar toda a divulgação e comunicação do congresso.',4),
 ('m05_palestrantes','Palestrantes e Conteúdo Científico','Gerenciar palestrantes, programação e conteúdo científico.',5),
 ('m06_av','Audiovisual e Tecnologia','Garantir toda a infraestrutura técnica, audiovisual e tecnológica.',6),
 ('m07_cenografia','Cenografia e Comunicação Visual','Executar a montagem física, os ambientes e a identidade visual do evento.',7),
 ('m08_credenciamento','Credenciamento e Atendimento','Preparar toda a estrutura de acesso e atendimento.',8),
 ('m09_hospitalidade','Hospitalidade e Experiência','Garantir conforto e experiência para congressistas, palestrantes e convidados.',9),
 ('m10_cerimonial','Cerimonial e Homenagens','Organizar a cerimônia oficial e as homenagens.',10),
 ('m11_operacao','Operação do Evento','Executar todas as atividades operacionais antes, durante e imediatamente após o congresso.',11),
 ('m12_posevento','Pós-Evento','Concluir atividades administrativas, financeiras, comerciais e estratégicas.',12)) AS m(mk, name, obj, so)
CROSS JOIN (SELECT id FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre') t
ON CONFLICT (template_id, module_key) DO NOTHING;

INSERT INTO public.checkpoint_templates (template_id, name, deadline_offset, decisor, criteria_go, criteria_nogo)
SELECT t.id, ga.n, ga.o, ga.d, 'Critérios do gate cumpridos e evidências anexadas.', 'Critérios não cumpridos ou sem evidência — decidir plano de correção antes de avançar.'
FROM (VALUES
 ('Estratégia aprovada',-300,'CEO'),
 ('Local contratado',-310,'CEO'),
 ('Orçamento aprovado',-300,'CEO'),
 ('Comercialização aberta',-220,'Comercial'),
 ('Comissão científica definida',-240,'Científico'),
 ('Programação macro validada',-200,'Científico'),
 ('Feira comercializada',-60,'Comercial'),
 ('Fornecedores críticos contratados',-75,'Produção'),
 ('Produção gráfica liberada',-45,'Design'),
 ('Operação técnica validada',-15,'Tecnologia'),
 ('Go/No-Go D-30',-30,'CEO'),
 ('Go/No-Go D-7',-7,'CEO'),
 ('Evento pronto para abertura',-1,'Diretor de Eventos'),
 ('DRE encerrado',30,'Financeiro'),
 ('Pós-mortem concluído',35,'Diretor de Eventos')) AS ga(n, o, d)
CROSS JOIN (SELECT id FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre') t
WHERE NOT EXISTS (SELECT 1 FROM public.checkpoint_templates ct WHERE ct.template_id = t.id AND ct.name = ga.n);

INSERT INTO public.supplier_categories (key, name)
SELECT c.k, c.n FROM (VALUES
 ('cenografia','Cenografia'),
 ('mobiliario','Mobiliário'),
 ('geradores','Geradores'),
 ('seguranca','Segurança'),
 ('brigadistas','Brigadistas'),
 ('ambulancia_medica','Ambulância e Cobertura Médica')) AS c(k, n)
WHERE NOT EXISTS (SELECT 1 FROM public.supplier_categories sc WHERE sc.key = c.k);

INSERT INTO public.suppliers (name, phone, email)
SELECT s.n, s.p, s.e FROM (VALUES
 ('LOBL Eventos','(61) 99149-8919','financeiro@lobleventos.com'),
 ('Mobicom Estruturas','(61) 3201-1210','contato@mobicomestruturas.com.br'),
 ('Tecnogera',NULL,NULL),
 ('Stemac Rental',NULL,NULL),
 ('Aggreko',NULL,NULL),
 ('Confederal Segurança',NULL,NULL),
 ('Brasília Segurança',NULL,NULL),
 ('Brigada Capital',NULL,NULL),
 ('Brasília Emergências',NULL,NULL),
 ('Brasil Emergências Médicas',NULL,NULL),
 ('Vida UTI',NULL,NULL)) AS s(n, p, e)
WHERE NOT EXISTS (SELECT 1 FROM public.suppliers sp WHERE lower(sp.name) = lower(s.n));

INSERT INTO public.supplier_category_links (supplier_id, category_id)
SELECT sp.id, sc.id FROM (VALUES
 ('LOBL Eventos','cenografia'),
 ('LOBL Eventos','mobiliario'),
 ('Mobicom Estruturas','cenografia'),
 ('Mobicom Estruturas','mobiliario'),
 ('Tecnogera','geradores'),
 ('Stemac Rental','geradores'),
 ('Aggreko','geradores'),
 ('Confederal Segurança','seguranca'),
 ('Brasília Segurança','seguranca'),
 ('Brigada Capital','brigadistas'),
 ('Brasília Emergências','brigadistas'),
 ('Brasília Emergências','ambulancia_medica'),
 ('Brasil Emergências Médicas','ambulancia_medica'),
 ('Vida UTI','ambulancia_medica')) AS l(sname, ckey)
JOIN public.suppliers sp ON lower(sp.name) = lower(l.sname)
JOIN public.supplier_categories sc ON sc.key = l.ckey
ON CONFLICT DO NOTHING;

INSERT INTO public.venue_suppliers (venue_id, supplier_id, credential_status)
SELECT v.id, sp.id, 'credenciado' FROM (VALUES
 ('LOBL Eventos'),
 ('Mobicom Estruturas'),
 ('Tecnogera'),
 ('Stemac Rental'),
 ('Aggreko'),
 ('Confederal Segurança'),
 ('Brasília Segurança'),
 ('Brigada Capital'),
 ('Brasília Emergências'),
 ('Brasil Emergências Médicas'),
 ('Vida UTI')) AS l(sname)
JOIN public.suppliers sp ON lower(sp.name) = lower(l.sname)
CROSS JOIN (SELECT id FROM public.venues WHERE name = 'Centro de Convenções Ulysses Guimarães') v
ON CONFLICT DO NOTHING;

WITH t AS (SELECT id FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre'),
rows_data(mk, tk, title, off, role, prio, phase, typ, parent, cond, crit, evid, fin, descr, sort) AS (VALUES
 ('m01_estrategia','strategy.city.define','Definir cidade do evento',-365,'CEO','critica','F0','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,1),
 ('m01_estrategia','strategy.date.define','Definir data do evento',-365,'CEO','critica','F0','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,2),
 ('m01_estrategia','strategy.theme.define','Definir tema oficial',-330,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,3),
 ('m01_estrategia','strategy.slogan.define','Definir slogan',-330,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m01_estrategia','strategy.visual_identity.define','Definir identidade visual',-320,'Design','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,5),
 ('m01_estrategia','strategy.key_visual.create','Criar Key Visual',-310,'Design','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m01_estrategia','strategy.brand_manual.create','Criar Manual da Marca',-300,'Design','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m01_estrategia','strategy.comms_strategy.define','Definir estratégia de comunicação',-300,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m01_estrategia','strategy.scientific_committee.define','Definir comissão científica',-320,'Científico','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,9),
 ('m01_estrategia','strategy.tracks.define','Definir eixos temáticos',-310,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m01_estrategia','strategy.macro_program.define','Definir programação macro',-300,'Científico','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,11),
 ('m01_estrategia','strategy.plenaries.count','Definir quantidade de plenárias',-300,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m01_estrategia','strategy.coordinators.define','Definir coordenadores científicos',-300,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,13),
 ('m01_estrategia','strategy.budget.define','Definir orçamento geral',-320,'Financeiro','critica','F0','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,14),
 ('m01_estrategia','strategy.revenue_goal.define','Definir meta de faturamento',-315,'CEO','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m01_estrategia','strategy.attendees_goal.define','Definir meta de inscritos',-315,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,16),
 ('m01_estrategia','strategy.sponsors_goal.define','Definir meta de patrocinadores',-315,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m01_estrategia','strategy.expo_goal.define','Definir meta da feira',-315,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,18),
 ('m01_estrategia','strategy.budget.approve','Aprovar orçamento',-300,'CEO','critica','F0','obrigatoria',NULL,NULL,'critica',true,NULL,NULL,19),
 ('m02_local','venue.reserve','Reservar o Centro de Convenções',-330,'Diretor de Eventos','critica','F0','obrigatoria',NULL,NULL,'critica',false,'Local',NULL,1),
 ('m02_local','venue.contract.payment_terms','Negociar condições de pagamento do contrato',-320,'Financeiro','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,2),
 ('m02_local','venue.contract.installments','Negociar parcelamento do contrato',-320,'Financeiro','media','F0','opcional',NULL,NULL,'normal',false,NULL,NULL,3),
 ('m02_local','venue.contract.sign','Assinar contrato do espaço',-310,'CEO','critica','F0','obrigatoria',NULL,NULL,'critica',true,'Local',NULL,4),
 ('m02_local','venue.rooms.count','Definir quantidade de salas',-300,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m02_local','venue.rooms.capacity','Definir capacidade das salas',-300,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m02_local','venue.hours.define','Definir horário de funcionamento',-290,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m02_local','venue.floorplan.technical','Levantar planta técnica',-240,'Produção','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,8),
 ('m02_local','venue.floorplan.electrical','Levantar planta elétrica',-240,'Produção','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,9),
 ('m02_local','venue.accessibility.verify','Verificar acessibilidade',-210,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m02_local','venue.parking.verify','Verificar estacionamento',-210,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m02_local','venue.event_insurance.verify','Verificar obrigatoriedade de seguro do evento',-180,'Produção','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,12),
 ('m02_local','venue.event_insurance.contract','Contratar seguro do evento',-150,'Produção','media','F1','condicional','venue.event_insurance.verify','sim','normal',false,'Local',NULL,13),
 ('m02_local','venue.dispatcher.verify','Verificar necessidade de despachante',-180,'Produção','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m02_local','venue.dispatcher.contract','Contratar despachante',-150,'Produção','media','F1','condicional','venue.dispatcher.verify','sim','normal',false,'Local',NULL,15),
 ('m02_local','venue.licenses.identify','Identificar licenças obrigatórias',-180,'Produção','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,16),
 ('m02_local','venue.fees.identify','Identificar taxas obrigatórias',-180,'Financeiro','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m02_local','venue.legal_releases.request','Solicitar liberações legais',-120,'Produção','alta','F1','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,18),
 ('m02_local','venue.legal_releases.track','Acompanhar liberações legais',-60,'Produção','alta','F2','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,19),
 ('m02_local','venue.fees.pay','Efetuar pagamento das taxas',-45,'Financeiro','media','F2','obrigatoria',NULL,NULL,'normal',true,'Local',NULL,20),
 ('m02_local','venue.hvac.verify','Verificar necessidade de climatizadores',-120,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,21),
 ('m02_local','venue.hvac.contract','Contratar climatizadores',-90,'Produção','media','F1','condicional','venue.hvac.verify','sim','normal',false,'Estrutura',NULL,22),
 ('m02_local','venue.sunshade.verify','Verificar necessidade de tapa-sol',-120,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,23),
 ('m02_local','venue.sunshade.contract','Contratar tapa-sol',-90,'Produção','media','F1','condicional','venue.sunshade.verify','sim','normal',false,'Estrutura',NULL,24),
 ('m03_comercial','sales.sponsor_targets.define','Definir patrocinadores-alvo',-300,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,1),
 ('m03_comercial','sales.quotas.define','Definir cotas de patrocínio',-290,'Comercial','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,2),
 ('m03_comercial','sales.quotas.pricing','Definir valores das cotas',-290,'Comercial','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,3),
 ('m03_comercial','sales.proposal.create','Criar proposta comercial',-280,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m03_comercial','sales.contract.create','Criar contrato de patrocínio',-280,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m03_comercial','sales.prospecting.run','Prospectar patrocinadores',-260,'Comercial','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,6),
 ('m03_comercial','sales.proposals.send','Enviar propostas comerciais',-250,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m03_comercial','sales.contracts.negotiate','Negociar contratos',-220,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m03_comercial','sales.contracts.sign','Assinar contratos de patrocínio',-180,'Comercial','alta','F0','obrigatoria',NULL,NULL,'alta',true,NULL,NULL,9),
 ('m03_comercial','sales.sponsor_materials.receive','Receber materiais dos patrocinadores',-60,'Comercial','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m03_comercial','expo.map.create','Criar mapa da feira',-180,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m03_comercial','expo.booths.sizing','Definir metragem dos estandes',-180,'Comercial','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m03_comercial','expo.booths.numbering','Numerar estandes',-150,'Comercial','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,13),
 ('m03_comercial','expo.sponsors.placement','Definir localização dos patrocinadores',-120,'Comercial','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m03_comercial','expo.map.update','Atualizar mapa da feira',-30,'Comercial','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m03_comercial','expo.builder.contract','Contratar montadora oficial dos estandes',-120,'Produção','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Feira',NULL,16),
 ('m03_comercial','expo.assembly.track','Acompanhar montagem dos estandes',-2,'Produção','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,17),
 ('m03_comercial','expo.storage.reserve','Reservar armazenamento para materiais dos expositores',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,18),
 ('m03_comercial','expo.storage.secure_area','Definir área segura de armazenamento',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,19),
 ('m03_comercial','expo.loaders.contract','Contratar carregadores',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,20),
 ('m03_comercial','expo.cleaning.contract','Contratar limpeza da feira',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,21),
 ('m03_comercial','expo.credential.structure','Montar estrutura de credenciamento da feira',-15,'Credenciamento','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,22),
 ('m03_comercial','expo.credential.desks','Produzir balcões de credenciamento da feira',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,23),
 ('m03_comercial','expo.credential.panel','Produzir painel de credenciamento da feira',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,24),
 ('m03_comercial','expo.wristbands.visitors','Produzir pulseiras de visitantes da feira',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,25),
 ('m04_marketing','mkt.landing.create','Criar landing page',-240,'Marketing','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,1),
 ('m04_marketing','mkt.site.create','Criar página oficial',-230,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,2),
 ('m04_marketing','mkt.hotmart.setup','Configurar Hotmart',-230,'Marketing','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,3),
 ('m04_marketing','mkt.payments.setup','Configurar meios de pagamento',-230,'Marketing','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,4),
 ('m04_marketing','mkt.batches.create','Criar lotes',-220,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m04_marketing','mkt.coupons.create','Criar cupons',-210,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m04_marketing','mkt.faq.create','Criar FAQ',-200,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m04_marketing','mkt.program.publish','Publicar programação científica',-180,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m04_marketing','mkt.site.update','Atualizar site',-150,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,9),
 ('m04_marketing','mkt.countdown.campaign','Produzir campanha de contagem regressiva',-120,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m04_marketing','mkt.speakers.promote','Divulgar palestrantes',-150,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m04_marketing','mkt.sponsors.promote','Divulgar patrocinadores',-140,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m04_marketing','mkt.exhibitors.promote','Divulgar empresas expositoras',-130,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,13),
 ('m04_marketing','mkt.program.promote','Divulgar programação',-120,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m04_marketing','mkt.backstage.content','Produzir conteúdo de bastidores',-90,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m04_marketing','mkt.batch_turn.campaign','Produzir campanha de virada de lote',-100,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,16),
 ('m04_marketing','mkt.batch_lastday.campaign','Produzir campanha de último dia do lote',-95,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m04_marketing','mkt.last_batches.campaign','Produzir campanha de últimos lotes',-30,'Marketing','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,18),
 ('m04_marketing','mkt.last_seats.campaign','Produzir campanha de últimas vagas',-15,'Marketing','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,19),
 ('m04_marketing','mkt.ads.awareness','Configurar campanhas de awareness',-180,'Marketing','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,20),
 ('m04_marketing','mkt.ads.conversion','Configurar campanhas de conversão',-120,'Marketing','alta','F1','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,21),
 ('m04_marketing','mkt.ads.remarketing','Configurar remarketing',-90,'Marketing','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,22),
 ('m04_marketing','mkt.email.confirmation','Enviar confirmação de inscrição',-60,'Marketing','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,23),
 ('m04_marketing','mkt.email.general_info','Enviar informações gerais',-30,'Marketing','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,24),
 ('m04_marketing','mkt.email.hotel','Enviar orientações sobre hotel',-30,'Marketing','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,25),
 ('m04_marketing','mkt.email.access','Enviar orientações de acesso',-7,'Marketing','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,26),
 ('m04_marketing','mkt.email.map','Enviar mapa do evento',-7,'Marketing','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,27),
 ('m04_marketing','mkt.email.credential','Enviar orientações de credenciamento',-5,'Marketing','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,28),
 ('m04_marketing','mkt.email.thanks','Enviar agradecimento',2,'Marketing','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,29),
 ('m04_marketing','mkt.nps.survey','Aplicar pesquisa NPS',3,'Marketing','alta','F6','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,30),
 ('m05_palestrantes','speakers.list.build','Levantar palestrantes convidados',-240,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,1),
 ('m05_palestrantes','speakers.invite','Convidar palestrantes',-220,'Científico','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,2),
 ('m05_palestrantes','speakers.confirm','Confirmar participação dos palestrantes',-200,'Científico','alta','F0','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,3),
 ('m05_palestrantes','speakers.photo.receive','Receber foto oficial',-180,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m05_palestrantes','speakers.bio.receive','Receber mini currículo',-180,'Científico','media','F0','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m05_palestrantes','speakers.topic.receive','Receber tema da palestra',-170,'Científico','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m05_palestrantes','speakers.title.receive','Receber título da palestra',-170,'Científico','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m05_palestrantes','speakers.tech_needs.receive','Receber necessidades técnicas',-150,'Científico','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m05_palestrantes','program.schedule.build','Montar programação científica',-140,'Científico','alta','F1','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,9),
 ('m05_palestrantes','program.schedule.validate','Validar horários',-130,'Científico','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m05_palestrantes','program.conflicts.avoid','Evitar conflitos entre palestras',-130,'Científico','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m05_palestrantes','speakers.flights.buy','Comprar passagens',-90,'Produção','alta','F1','obrigatoria',NULL,NULL,'alta',false,'Palestrantes',NULL,12),
 ('m05_palestrantes','speakers.hotels.reserve','Reservar hotéis',-90,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,'Palestrantes',NULL,13),
 ('m05_palestrantes','speakers.briefing.send','Enviar orientações aos palestrantes',-30,'Científico','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m05_palestrantes','speakers.arrival.confirm','Confirmar chegada',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m05_palestrantes','speakers.lodging.confirm','Confirmar hospedagem',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,16),
 ('m05_palestrantes','speakers.presentation.confirm','Confirmar apresentação',-7,'Científico','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m05_palestrantes','speakers.final_file.receive','Receber arquivo final da palestra',-3,'Científico','media','F4','opcional',NULL,NULL,'normal',false,NULL,NULL,18),
 ('m06_av','av.sound.contract','Contratar sonorização',-120,'Tecnologia','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Audiovisual',NULL,1),
 ('m06_av','av.lighting.contract','Contratar iluminação',-120,'Tecnologia','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Audiovisual',NULL,2),
 ('m06_av','av.led.measurements','Levantar medidas dos painéis de LED de cada auditório',-110,'Tecnologia','alta','F1','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,3),
 ('m06_av','av.led.quotes','Solicitar orçamento dos painéis de LED',-100,'Tecnologia','media','F1','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m06_av','av.led.contract','Contratar painéis de LED',-90,'Tecnologia','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Audiovisual',NULL,5),
 ('m06_av','av.recording.contract','Contratar gravação das plenárias',-90,'Tecnologia','media','F1','obrigatoria',NULL,NULL,'normal',false,'Audiovisual',NULL,6),
 ('m06_av','av.internet.contract','Contratar internet exclusiva',-90,'Tecnologia','alta','F1','obrigatoria',NULL,NULL,'alta',false,'Tecnologia',NULL,7),
 ('m06_av','av.internet_backup.verify','Verificar necessidade de internet backup',-80,'Tecnologia','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m06_av','av.internet_backup.contract','Contratar internet backup',-60,'Tecnologia','media','F2','condicional','av.internet_backup.verify','sim','normal',false,'Tecnologia',NULL,9),
 ('m06_av','av.ups.verify','Verificar necessidade de nobreak',-80,'Tecnologia','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m06_av','av.ups.contract','Contratar nobreak',-60,'Tecnologia','media','F2','condicional','av.ups.verify','sim','normal',false,'Tecnologia',NULL,11),
 ('m06_av','av.radios.quantity','Definir quantidade de rádios',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m06_av','av.radios.contract','Contratar rádios',-45,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Tecnologia',NULL,13),
 ('m06_av','av.generator.contract','Contratar gerador principal',-60,'Produção','critica','F2','obrigatoria',NULL,NULL,'critica',false,'Estrutura',NULL,14),
 ('m06_av','av.generator_backup.verify','Verificar necessidade de gerador backup',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m06_av','av.generator_backup.contract','Contratar gerador backup',-45,'Produção','media','F2','condicional','av.generator_backup.verify','sim','normal',false,'Estrutura',NULL,16),
 ('m06_av','av.temp_power.verify','Verificar necessidade de energia elétrica temporária',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m06_av','av.temp_power.contract','Contratar energia elétrica temporária',-45,'Produção','media','F2','condicional','av.temp_power.verify','sim','normal',false,'Estrutura',NULL,18),
 ('m06_av','av.microphones.provide','Disponibilizar microfones',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,19),
 ('m06_av','av.clickers.provide','Disponibilizar clickers',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,20),
 ('m06_av','av.laptops_backup.provide','Disponibilizar notebooks de backup',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,21),
 ('m06_av','av.stage_monitor.provide','Disponibilizar retorno de palco',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,22),
 ('m06_av','av.operators.provide','Disponibilizar operadores técnicos',-15,'Tecnologia','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,23),
 ('m06_av','av.tech_tests.run','Realizar testes técnicos',-2,'Tecnologia','critica','F4','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,24),
 ('m06_av','av.soundcheck.run','Realizar passagem de som',-1,'Tecnologia','critica','F4','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,25))
INSERT INTO public.template_tasks (template_id, module_key, task_key, title, day_offset, responsible_role, priority, phase_code, task_type, conditional_parent_key, condition_value, criticality, evidence_required, finance_category, description, sort_order, area)
SELECT t.id, r.mk, r.tk, r.title, r.off::int, r.role, r.prio, r.phase, r.typ, r.parent, r.cond, r.crit, r.evid::boolean, r.fin, r.descr, r.sort::int, r.role FROM rows_data r CROSS JOIN t
ON CONFLICT (template_id, task_key) WHERE task_key IS NOT NULL DO NOTHING;

WITH t AS (SELECT id FROM public.templates WHERE name = 'Congresso Science Play · POP Mestre'),
rows_data(mk, tk, title, off, role, prio, phase, typ, parent, cond, crit, evid, fin, descr, sort) AS (VALUES
 ('m07_cenografia','cv.scenography.contract','Contratar empresa de cenografia',-120,'Produção','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Cenografia',NULL,1),
 ('m07_cenografia','cv.furniture.contract','Contratar mobiliário',-90,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,2),
 ('m07_cenografia','cv.furniture_golden.contract','Contratar mobiliário da Área Golden/VIP',-90,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,3),
 ('m07_cenografia','cv.portal.art','Desenvolver arte do pórtico principal',-90,'Design','alta','F1','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,4),
 ('m07_cenografia','cv.portal.produce','Produzir pórtico principal',-60,'Produção','alta','F2','obrigatoria',NULL,NULL,'alta',false,'Cenografia',NULL,5),
 ('m07_cenografia','cv.queue_poles.contract','Contratar unifilas',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,6),
 ('m07_cenografia','cv.grid.contract','Contratar estrutura Grid',-75,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,7),
 ('m07_cenografia','golden.banner.produce','Produzir lona da Área Golden',-60,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,8),
 ('m07_cenografia','golden.banner_structure.contract','Contratar estrutura para instalação da lona',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,9),
 ('m07_cenografia','golden.carpet.contract','Contratar carpete da Área Golden',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,10),
 ('m07_cenografia','cv.photo_panel.produce','Produzir painel para fotos',-45,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,11),
 ('m07_cenografia','cv.letters.contract','Contratar letras-caixa',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,12),
 ('m07_cenografia','cv.instagrammable.setup','Montar espaço instagramável',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,13),
 ('m07_cenografia','cv.puffs.provide','Disponibilizar puffs decorativos',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m07_cenografia','cv.wristbands_main.produce','Produzir pulseiras da Plenária Principal',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,15),
 ('m07_cenografia','cv.wristbands_day.produce','Produzir pulseiras das plenárias de um dia',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,16),
 ('m07_cenografia','golden.credentials.produce','Produzir credenciais Golden',-21,'Design','alta','F3','obrigatoria',NULL,NULL,'alta',false,'Credenciamento',NULL,17),
 ('m07_cenografia','cv.credentials_vip.produce','Produzir credenciais VIP',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,18),
 ('m07_cenografia','cv.credentials_speakers.produce','Produzir credenciais dos palestrantes',-21,'Design','alta','F3','obrigatoria',NULL,NULL,'alta',false,'Credenciamento',NULL,19),
 ('m07_cenografia','cv.credentials_production.separate','Separar credenciais da produção',-15,'Credenciamento','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,20),
 ('m07_cenografia','cv.credentials_exhibitors.produce','Produzir credenciais dos expositores',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,21),
 ('m07_cenografia','cv.lanyards.produce','Produzir cordões',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,22),
 ('m07_cenografia','cv.notebooks.produce','Produzir cadernos',-45,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Brindes',NULL,23),
 ('m07_cenografia','cv.pens.produce','Produzir canetas',-45,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Brindes',NULL,24),
 ('m07_cenografia','cv.bags.produce','Produzir sacolas',-45,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Brindes',NULL,25),
 ('m07_cenografia','cv.program_totems.produce','Produzir totens de programação',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,26),
 ('m07_cenografia','cv.program_printed.produce','Produzir programação impressa de cada plenária',-14,'Design','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,27),
 ('m07_cenografia','cv.program_rooms.install','Instalar programação na entrada das salas',-1,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,28),
 ('m07_cenografia','cv.signage_totems.produce','Produzir totens de sinalização',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,29),
 ('m07_cenografia','cv.signage_plates.produce','Produzir placas de orientação',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cenografia',NULL,30),
 ('m07_cenografia','cv.vip_chairs.identify','Produzir identificação de cadeiras VIP reservadas',-7,'Produção','media','F4','opcional',NULL,NULL,'normal',false,NULL,NULL,31),
 ('m07_cenografia','golden.chair_covers.separate','Separar capas das cadeiras Golden',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,32),
 ('m07_cenografia','cv.install.check','Conferir instalação da comunicação visual',-1,'Produção','alta','F4','obrigatoria',NULL,NULL,'alta',true,NULL,NULL,33),
 ('m08_credenciamento','cred.headcount.estimate','Levantar quantitativo de congressistas',-60,'Credenciamento','alta','F2','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,1),
 ('m08_credenciamento','cred.structure.setup','Montar estrutura de credenciamento',-30,'Credenciamento','alta','F3','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,2),
 ('m08_credenciamento','cred.desks.produce','Produzir balcões',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,3),
 ('m08_credenciamento','cred.panel.produce','Produzir painel de credenciamento',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,4),
 ('m08_credenciamento','cred.laptops.provide','Disponibilizar notebooks',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m08_credenciamento','cred.printers.provide','Disponibilizar impressoras',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m08_credenciamento','cred.internet.provide','Disponibilizar internet do credenciamento',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m08_credenciamento','cred.readers.provide','Disponibilizar leitores',-7,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m08_credenciamento','cred.badges.produce','Produzir crachás',-14,'Design','alta','F4','obrigatoria',NULL,NULL,'alta',false,'Credenciamento',NULL,9),
 ('m08_credenciamento','cred.wristbands.produce','Produzir pulseiras para visitantes',-14,'Design','media','F4','obrigatoria',NULL,NULL,'normal',false,'Credenciamento',NULL,10),
 ('m08_credenciamento','cred.lanyards.organize','Organizar cordões',-7,'Credenciamento','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m08_credenciamento','cred.team.prepare','Preparar equipe de credenciamento',-7,'Credenciamento','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m08_credenciamento','cred.simulation.run','Simular credenciamento',-2,'Credenciamento','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,13),
 ('m08_credenciamento','cred.open','Abrir credenciamento',0,'Credenciamento','critica','F5','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,14),
 ('m08_credenciamento','cred.service.manage','Gerenciar atendimento',0,'Credenciamento','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15),
 ('m08_credenciamento','cred.exceptions.manage','Gerenciar exceções de acesso',0,'Credenciamento','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,16),
 ('m09_hospitalidade','hosp.golden_coffee.contract','Contratar coffee break da Área Golden',-60,'Hospitalidade','alta','F2','obrigatoria',NULL,NULL,'alta',false,'Hospitalidade',NULL,1),
 ('m09_hospitalidade','hosp.stage_water.provide','Disponibilizar água mineral no palco',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,2),
 ('m09_hospitalidade','hosp.speaker_bottles.provide','Disponibilizar garrafas para palestrantes',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,3),
 ('m09_hospitalidade','hosp.speaker_glasses.provide','Disponibilizar taças para palestrantes',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m09_hospitalidade','hosp.stage_check.run','Conferir abastecimento antes de cada palestra',0,'Hospitalidade','alta','F5','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,5),
 ('m09_hospitalidade','hosp.massage.contract','Contratar serviço de massagem',-30,'Hospitalidade','media','F3','obrigatoria',NULL,NULL,'normal',false,'Hospitalidade',NULL,6),
 ('m09_hospitalidade','hosp.charger_totem.contract','Contratar totem carregador de celular',-30,'Hospitalidade','media','F3','obrigatoria',NULL,NULL,'normal',false,'Hospitalidade',NULL,7),
 ('m09_hospitalidade','hosp.golden_puffs.provide','Disponibilizar puffs da Área Golden',-7,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m09_hospitalidade','hosp.photo_space.setup','Montar espaço para fotos',-1,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,9),
 ('m09_hospitalidade','hosp.experience.check','Conferir funcionamento dos serviços de experiência',0,'Hospitalidade','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m10_cerimonial','cer.mc.contract','Contratar mestre de cerimônias',-90,'Produção','alta','F1','obrigatoria',NULL,NULL,'alta',false,'Cerimonial',NULL,1),
 ('m10_cerimonial','cer.script.write','Elaborar roteiro',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,2),
 ('m10_cerimonial','cer.script.validate','Validar roteiro',-15,'CEO','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,3),
 ('m10_cerimonial','cer.trophies.produce','Produzir troféus',-30,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cerimonial',NULL,4),
 ('m10_cerimonial','cer.honorees.validate','Validar lista de homenageados',-21,'CEO','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m10_cerimonial','cer.names.check','Conferir grafia dos nomes',-14,'Produção','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,6),
 ('m10_cerimonial','cer.delivery.organize','Organizar entrega das homenagens',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m10_cerimonial','cer.owners.define','Definir responsáveis do cerimonial',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m10_cerimonial','cer.rehearsal.run','Ensaiar cerimônia',-1,'Produção','media','F4','opcional',NULL,NULL,'normal',false,NULL,NULL,9),
 ('m11_operacao','ops.suppliers.confirm','Confirmar fornecedores',-15,'Produção','critica','F3','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,1),
 ('m11_operacao','ops.team.confirm','Confirmar equipe operacional',-15,'Produção','alta','F3','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,2),
 ('m11_operacao','ops.hotels.confirm','Confirmar hotéis',-15,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,3),
 ('m11_operacao','ops.flights.confirm','Confirmar passagens',-15,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,4),
 ('m11_operacao','ops.assembly.start','Iniciar montagem',-3,'Produção','critica','F4','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,5),
 ('m11_operacao','ops.electrical.check','Conferir instalações elétricas',-2,'Produção','critica','F4','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,6),
 ('m11_operacao','ops.internet.check','Conferir internet',-2,'Tecnologia','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,7),
 ('m11_operacao','ops.scenography.check','Conferir cenografia',-2,'Produção','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,8),
 ('m11_operacao','ops.general_tests.run','Realizar testes gerais',-2,'Produção','critica','F4','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,9),
 ('m11_operacao','ops.soundcheck.run','Realizar passagem de som geral',-1,'Tecnologia','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m11_operacao','ops.credential_simulation.run','Simular credenciamento geral',-1,'Credenciamento','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m11_operacao','ops.rooms.check','Conferir salas',-1,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,12),
 ('m11_operacao','ops.general_meeting.run','Realizar reunião geral',-1,'Diretor de Eventos','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,13),
 ('m11_operacao','ops.team_kits.deliver','Entregar kits da equipe',-1,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m11_operacao','ops.briefing.run','Realizar briefing operacional',-1,'Produção','alta','F4','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,15),
 ('m11_operacao','ops.credential.open','Abrir credenciamento no dia',0,'Credenciamento','critica','F5','obrigatoria',NULL,NULL,'critica',false,NULL,NULL,16),
 ('m11_operacao','ops.team.position','Posicionar equipe',0,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,17),
 ('m11_operacao','ops.rooms.release','Liberar salas',0,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,18),
 ('m11_operacao','ops.exhibitors.release','Liberar expositores',0,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,19),
 ('m11_operacao','ops.program.track','Acompanhar programação',0,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,20),
 ('m11_operacao','ops.speakers.track','Acompanhar palestrantes',0,'Científico','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,21),
 ('m11_operacao','ops.exhibitors.track','Acompanhar expositores',0,'Comercial','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,22),
 ('m11_operacao','ops.suppliers.manage','Gerenciar fornecedores',0,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,23),
 ('m11_operacao','ops.incidents.manage','Gerenciar incidentes',0,'Produção','alta','F5','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,24),
 ('m11_operacao','ops.rooms.close','Encerrar atividades das salas',1,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,25),
 ('m11_operacao','ops.teardown.track','Acompanhar desmontagem',1,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,26),
 ('m11_operacao','ops.equipment.check','Conferir equipamentos',1,'Produção','media','F5','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,27),
 ('m11_operacao','ops.materials.check','Conferir materiais',2,'Produção','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,28),
 ('m12_posevento','postevent.invoices.receive','Receber notas fiscais',7,'Financeiro','alta','F6','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,1),
 ('m12_posevento','postevent.contracts.check','Conferir contratos',10,'Financeiro','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,2),
 ('m12_posevento','postevent.payments.execute','Efetuar pagamentos',15,'Financeiro','critica','F6','obrigatoria',NULL,NULL,'critica',true,NULL,NULL,3),
 ('m12_posevento','postevent.dre.close','Fechar DRE',30,'Financeiro','critica','F6','obrigatoria',NULL,NULL,'critica',true,NULL,NULL,4),
 ('m12_posevento','postevent.certificates.issue','Emitir certificados',10,'Marketing','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,5),
 ('m12_posevento','postevent.photos.publish','Publicar fotos',7,'Marketing','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,6),
 ('m12_posevento','postevent.videos.publish','Publicar vídeos',14,'Marketing','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,7),
 ('m12_posevento','postevent.sponsors_report.build','Elaborar relatório para patrocinadores',21,'Comercial','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,8),
 ('m12_posevento','postevent.expo_report.build','Elaborar relatório da feira',21,'Comercial','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,9),
 ('m12_posevento','postevent.leads.consolidate','Consolidar leads',14,'Comercial','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,10),
 ('m12_posevento','postevent.renewal.plan','Planejar renovação da próxima edição',30,'Comercial','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,11),
 ('m12_posevento','postevent.postmortem.run','Realizar reunião de pós-mortem',21,'Diretor de Eventos','alta','F6','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,12),
 ('m12_posevento','postevent.lessons.record','Registrar lições aprendidas',25,'Diretor de Eventos','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,13),
 ('m12_posevento','postevent.pop.update','Atualizar POP com base nas lições',30,'Diretor de Eventos','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,14),
 ('m12_posevento','postevent.docs.archive','Arquivar documentos',45,'Financeiro','media','F6','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,15))
INSERT INTO public.template_tasks (template_id, module_key, task_key, title, day_offset, responsible_role, priority, phase_code, task_type, conditional_parent_key, condition_value, criticality, evidence_required, finance_category, description, sort_order, area)
SELECT t.id, r.mk, r.tk, r.title, r.off::int, r.role, r.prio, r.phase, r.typ, r.parent, r.cond, r.crit, r.evid::boolean, r.fin, r.descr, r.sort::int, r.role FROM rows_data r CROSS JOIN t
ON CONFLICT (template_id, task_key) WHERE task_key IS NOT NULL DO NOTHING;

WITH t AS (SELECT id FROM public.templates WHERE name = 'Nutrição Brasil Brasília · Ulysses Guimarães'),
rows_data(mk, tk, title, off, role, prio, phase, typ, parent, cond, crit, evid, fin, descr, sort) AS (VALUES
 ('m02_local','venue.reserve','Reservar o Centro de Convenções Ulysses Guimarães',-330,'Diretor de Eventos','critica','F0','obrigatoria',NULL,NULL,'critica',false,'Local','Local padrão da edição Brasília: Centro de Convenções Ulysses Guimarães.',1),
 ('m06_av','av.internet.contract','Contratar internet exclusiva (preferencial: Wixx)',-90,'Tecnologia','alta','F1','obrigatoria',NULL,NULL,'alta',false,'Tecnologia','Internet principal preferencial: Wixx, quando contratualmente aplicável.',2),
 ('m07_cenografia','cv.grid.contract','Contratar estrutura Grid Q20 da Área Golden',-75,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Especificação da edição Brasília: estrutura Grid Q20 para a Área Golden.',3),
 ('m07_cenografia','golden.banner.produce','Produzir lona da Área Golden (NB Brasília)',-60,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Lona da Área Golden conforme identidade NB Brasília.',4),
 ('m07_cenografia','golden.banner_structure.contract','Contratar estrutura de instalação da lona Golden',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Estrutura para instalação da lona da Área Golden no Ulysses Guimarães.',5),
 ('m07_cenografia','golden.carpet.contract','Contratar carpete da Área Golden (NB Brasília)',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Carpete exclusivo da Área Golden.',6),
 ('m07_cenografia','cv.furniture_golden.contract','Contratar mobiliário da Área Golden/VIP (NB Brasília)',-90,'Produção','media','F1','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Mobiliário premium da Área Golden, incluindo puffs.',7),
 ('m07_cenografia','golden.chair_covers.separate','Separar capas das cadeiras Golden (NB Brasília)',-7,'Produção','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,'Capas das cadeiras da Área Golden — conferir quantitativo da edição.',8),
 ('m07_cenografia','golden.credentials.produce','Produzir credenciais Golden (NB Brasília)',-21,'Design','alta','F3','obrigatoria',NULL,NULL,'alta',false,'Credenciamento','Credenciamento próprio da Área Golden.',9),
 ('m07_cenografia','cv.letters.contract','Produzir letras-caixa NB',-60,'Produção','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Letras-caixa com a marca NB — comunicação visual específica da edição.',10),
 ('m07_cenografia','cv.portal.produce','Produzir pórtico principal (NB Brasília)',-60,'Produção','alta','F2','obrigatoria',NULL,NULL,'alta',false,'Cenografia','Pórtico principal com identidade NB Brasília.',11),
 ('m07_cenografia','cv.photo_panel.produce','Produzir painel para fotos (NB Brasília)',-45,'Design','media','F2','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Painel para fotos com identidade da edição.',12),
 ('m07_cenografia','cv.instagrammable.setup','Montar espaço instagramável (NB Brasília)',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,'Espaço instagramável específico da edição.',13),
 ('m07_cenografia','cv.program_totems.produce','Produzir totens de programação (NB Brasília)',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Totens de programação por plenária.',14),
 ('m07_cenografia','cv.signage_plates.produce','Produzir sinalização das plenárias (NB Brasília)',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Cenografia','Sinalização das plenárias no Ulysses Guimarães.',15),
 ('m07_cenografia','cv.vip_chairs.identify','Produzir identificação de cadeiras reservadas (NB Brasília)',-7,'Produção','media','F4','opcional',NULL,NULL,'normal',false,NULL,'Identificação de cadeiras reservadas/VIP nas plenárias.',16),
 ('m07_cenografia','cv.program_printed.produce','Produzir programação impressa por plenária (NB Brasília)',-14,'Design','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,'Programação impressa instalada na entrada de cada sala.',17),
 ('m03_comercial','expo.builder.contract','Contratar montadora oficial da feira (NB Brasília)',-120,'Produção','critica','F1','obrigatoria',NULL,NULL,'critica',false,'Feira','Montadora oficial dos estandes da feira NB Brasília.',18),
 ('m03_comercial','expo.credential.structure','Montar credenciamento próprio da feira (NB Brasília)',-15,'Credenciamento','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,'A feira possui credenciamento próprio, separado do congresso.',19),
 ('m03_comercial','expo.storage.reserve','Reservar armazenamento de expositores (NB Brasília)',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,'Armazenamento de materiais dos expositores no Ulysses Guimarães.',20),
 ('m03_comercial','expo.storage.secure_area','Definir área segura de armazenamento (NB Brasília)',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,NULL,'Área segura para materiais de expositores.',21),
 ('m03_comercial','expo.cleaning.contract','Contratar limpeza da feira (NB Brasília)',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,22),
 ('m03_comercial','expo.loaders.contract','Contratar carregadores (NB Brasília)',-30,'Produção','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,23),
 ('m03_comercial','expo.wristbands.visitors','Produzir pulseiras de visitantes da feira (NB Brasília)',-21,'Design','media','F3','obrigatoria',NULL,NULL,'normal',false,'Feira',NULL,24),
 ('m09_hospitalidade','hosp.golden_coffee.contract','Contratar coffee break da Área Golden (NB Brasília)',-60,'Hospitalidade','alta','F2','obrigatoria',NULL,NULL,'alta',false,'Hospitalidade','Coffee break exclusivo da Área Golden.',25),
 ('m09_hospitalidade','hosp.massage.contract','Contratar massagem da Área Golden (NB Brasília)',-30,'Hospitalidade','media','F3','obrigatoria',NULL,NULL,'normal',false,'Hospitalidade','Serviço de massagem na Área Golden.',26),
 ('m09_hospitalidade','hosp.golden_puffs.provide','Disponibilizar puffs da Área Golden (NB Brasília)',-7,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,'Puffs da experiência premium Golden.',27),
 ('m09_hospitalidade','hosp.stage_water.provide','Disponibilizar água mineral no palco (NB Brasília)',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,'Hospitalidade de palco: água mineral em todas as plenárias.',28),
 ('m09_hospitalidade','hosp.speaker_bottles.provide','Disponibilizar garrafas para palestrantes (NB Brasília)',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,29),
 ('m09_hospitalidade','hosp.speaker_glasses.provide','Disponibilizar taças para palestrantes (NB Brasília)',-1,'Hospitalidade','media','F4','obrigatoria',NULL,NULL,'normal',false,NULL,NULL,30),
 ('m09_hospitalidade','hosp.stage_check.run','Conferir abastecimento antes de cada palestra (NB Brasília)',0,'Hospitalidade','alta','F5','obrigatoria',NULL,NULL,'alta',false,NULL,NULL,31))
INSERT INTO public.template_tasks (template_id, module_key, task_key, title, day_offset, responsible_role, priority, phase_code, task_type, conditional_parent_key, condition_value, criticality, evidence_required, finance_category, description, sort_order, area)
SELECT t.id, r.mk, r.tk, r.title, r.off::int, r.role, r.prio, r.phase, r.typ, r.parent, r.cond, r.crit, r.evid::boolean, r.fin, r.descr, r.sort::int, r.role FROM rows_data r CROSS JOIN t
ON CONFLICT (template_id, task_key) WHERE task_key IS NOT NULL DO NOTHING;
