-- ============================================================
-- SCIENCE PLAY OS — SEED: POP TEMPLATES (Procedimentos Operacionais Padrão)
-- Execute APÓS o supabase-schema.sql
-- ============================================================

-- Limpar templates existentes (caso re-execute)
DELETE FROM public.pop_templates;

-- ============================================================
-- TEMPLATE: IMERSÃO (ex: PALESTRE•SE, Golden)
-- 95 tarefas — nível operação real
-- ============================================================
INSERT INTO public.pop_templates (name, event_type, tasks) VALUES (
  'Imersão Premium (PALESTRE•SE / Golden)',
  'imersao',
  '[
    {"title": "Definir data e cidade do evento", "department": "ADM", "day_offset": -120, "priority": "urgente"},
    {"title": "Reservar venue / espaço principal (contrato)", "department": "PROD", "day_offset": -120, "priority": "urgente"},
    {"title": "Definir meta de receita e número de vagas", "department": "FIN", "day_offset": -110, "priority": "alta"},
    {"title": "Criar estrutura de lotes e preços", "department": "VND", "day_offset": -110, "priority": "alta"},
    {"title": "Montar página de vendas (copy + design)", "department": "MKT", "day_offset": -100, "priority": "urgente"},
    {"title": "Configurar produto na Hotmart/plataforma", "department": "VND", "day_offset": -100, "priority": "alta"},
    {"title": "Definir palestrantes/mentores convidados", "department": "ADM", "day_offset": -100, "priority": "alta"},
    {"title": "Enviar convites formais aos palestrantes", "department": "ADM", "day_offset": -95, "priority": "alta"},
    {"title": "Negociar cachês e condições", "department": "FIN", "day_offset": -90, "priority": "alta"},
    {"title": "Assinar contratos com palestrantes", "department": "ADM", "day_offset": -85, "priority": "alta"},
    {"title": "Criar identidade visual do evento (KV)", "department": "MKT", "day_offset": -90, "priority": "alta"},
    {"title": "Produzir criativos para tráfego (estáticos + vídeo)", "department": "MKT", "day_offset": -85, "priority": "alta"},
    {"title": "Montar estratégia de tráfego pago (Meta + Google)", "department": "MKT", "day_offset": -85, "priority": "alta"},
    {"title": "Configurar pixel e conversões na LP", "department": "MKT", "day_offset": -83, "priority": "alta"},
    {"title": "Iniciar campanhas de tráfego — Lote 1", "department": "MKT", "day_offset": -80, "priority": "urgente"},
    {"title": "Criar sequência de emails de lançamento", "department": "MKT", "day_offset": -80, "priority": "alta"},
    {"title": "Montar grupo de WhatsApp dos inscritos", "department": "ATD", "day_offset": -75, "priority": "normal"},
    {"title": "Criar automação de boas-vindas pós-compra", "department": "ATD", "day_offset": -75, "priority": "alta"},
    {"title": "Publicar stories/reels de abertura de vendas", "department": "MKT", "day_offset": -80, "priority": "alta"},
    {"title": "Gravar depoimentos de alunos anteriores", "department": "MKT", "day_offset": -75, "priority": "normal"},
    {"title": "Campanha de indicação (Member Get Member)", "department": "MKT", "day_offset": -70, "priority": "normal"},
    {"title": "Revisar e ajustar copy da página de vendas", "department": "MKT", "day_offset": -60, "priority": "normal"},
    {"title": "Virada de lote 1 → lote 2 (urgência)", "department": "VND", "day_offset": -60, "priority": "urgente"},
    {"title": "Email + WhatsApp avisando virada de lote", "department": "MKT", "day_offset": -60, "priority": "alta"},
    {"title": "Escalar tráfego com melhores criativos", "department": "MKT", "day_offset": -55, "priority": "alta"},
    {"title": "Orçar e contratar empresa de audiovisual", "department": "PROD", "day_offset": -60, "priority": "alta"},
    {"title": "Orçar e contratar coffee break / alimentação", "department": "PROD", "day_offset": -60, "priority": "alta"},
    {"title": "Orçar e contratar fotógrafo + videomaker", "department": "PROD", "day_offset": -55, "priority": "normal"},
    {"title": "Definir necessidades de materiais impressos", "department": "PROD", "day_offset": -50, "priority": "normal"},
    {"title": "Orçar e produzir crachás / credenciais", "department": "PROD", "day_offset": -45, "priority": "normal"},
    {"title": "Produzir apostila / material didático", "department": "PROD", "day_offset": -45, "priority": "alta"},
    {"title": "Contratar equipe de recepção / apoio", "department": "PROD", "day_offset": -40, "priority": "normal"},
    {"title": "Reservar bloco de quartos em hotel parceiro", "department": "PROD", "day_offset": -50, "priority": "alta"},
    {"title": "Comprar passagens aéreas (equipe + palestrantes)", "department": "FIN", "day_offset": -45, "priority": "alta"},
    {"title": "Organizar transfers aeroporto-hotel-venue", "department": "PROD", "day_offset": -40, "priority": "normal"},
    {"title": "Montar cronograma/roteiro completo do evento", "department": "PROD", "day_offset": -40, "priority": "urgente"},
    {"title": "Enviar briefing aos palestrantes (horários, tema, formato)", "department": "PROD", "day_offset": -35, "priority": "alta"},
    {"title": "Virada de lote 2 → lote 3 (últimas vagas)", "department": "VND", "day_offset": -30, "priority": "urgente"},
    {"title": "Campanha de escassez — últimas vagas", "department": "MKT", "day_offset": -30, "priority": "urgente"},
    {"title": "Email sequência de urgência (D-30 a D-7)", "department": "MKT", "day_offset": -30, "priority": "alta"},
    {"title": "Confirmar presença de todos os palestrantes", "department": "ADM", "day_offset": -25, "priority": "alta"},
    {"title": "Fechar contrato final com venue (detalhes técnicos)", "department": "PROD", "day_offset": -25, "priority": "alta"},
    {"title": "Testar projeção, som e iluminação no espaço", "department": "PROD", "day_offset": -20, "priority": "alta"},
    {"title": "Produzir conteúdo de bastidores (expectativa)", "department": "MKT", "day_offset": -20, "priority": "normal"},
    {"title": "Campanha de WhatsApp para leads que não compraram", "department": "MKT", "day_offset": -15, "priority": "alta"},
    {"title": "Enviar email logístico aos inscritos (endereço, horário, dress code)", "department": "ATD", "day_offset": -14, "priority": "urgente"},
    {"title": "Criar grupo exclusivo dos participantes", "department": "ATD", "day_offset": -14, "priority": "alta"},
    {"title": "Confirmar serviço de coffee break (menu + horários)", "department": "PROD", "day_offset": -10, "priority": "alta"},
    {"title": "Enviar material de apoio/pré-work aos participantes", "department": "ATD", "day_offset": -10, "priority": "normal"},
    {"title": "Fechar DRE provisório (custos vs receita até o momento)", "department": "FIN", "day_offset": -10, "priority": "alta"},
    {"title": "Fechar vendas — encerrar inscrições", "department": "VND", "day_offset": -7, "priority": "urgente"},
    {"title": "Montar lista final de participantes + check-in", "department": "ATD", "day_offset": -7, "priority": "urgente"},
    {"title": "Imprimir crachás com nomes finais", "department": "PROD", "day_offset": -5, "priority": "alta"},
    {"title": "Separar e organizar kits/materiais por participante", "department": "PROD", "day_offset": -5, "priority": "alta"},
    {"title": "Confirmar transfers e logística de transporte", "department": "PROD", "day_offset": -5, "priority": "alta"},
    {"title": "Montar apresentações finais (slides, vídeos)", "department": "PROD", "day_offset": -5, "priority": "alta"},
    {"title": "Enviar lembrete WhatsApp + email (D-3)", "department": "ATD", "day_offset": -3, "priority": "alta"},
    {"title": "Conferir checklist completo do venue", "department": "PROD", "day_offset": -2, "priority": "urgente"},
    {"title": "Preparar cenário/palco (banner, backdrop, flores)", "department": "PROD", "day_offset": -1, "priority": "urgente"},
    {"title": "Reunião final com equipe (alinhamento geral)", "department": "ADM", "day_offset": -1, "priority": "urgente"},
    {"title": "Testar som + projeção + internet no local", "department": "PROD", "day_offset": -1, "priority": "urgente"},
    {"title": "Organizar mesa de credenciamento", "department": "ATD", "day_offset": -1, "priority": "alta"},
    {"title": "Receber equipe AV e alinhar passagens de slides", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Abertura: check-in dos participantes", "department": "ATD", "day_offset": 0, "priority": "urgente"},
    {"title": "Registrar fotos e vídeos (stories ao vivo)", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Acompanhar timeline do evento (horários)", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Coletar depoimentos em vídeo durante o evento", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Resolver imprevistos operacionais em tempo real", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Distribuir formulário NPS/feedback no final", "department": "ATD", "day_offset": 0, "priority": "alta"},
    {"title": "Enviar email/WhatsApp de agradecimento (D+1)", "department": "ATD", "day_offset": 1, "priority": "urgente"},
    {"title": "Postar conteúdo de encerramento nas redes", "department": "MKT", "day_offset": 1, "priority": "alta"},
    {"title": "Enviar certificado de participação", "department": "ATD", "day_offset": 2, "priority": "alta"},
    {"title": "Entregar gravações/material extra prometido", "department": "ATD", "day_offset": 3, "priority": "alta"},
    {"title": "Compilar resultados do NPS/feedback", "department": "ATD", "day_offset": 3, "priority": "normal"},
    {"title": "Editar vídeo de aftermovie / highlights", "department": "MKT", "day_offset": 5, "priority": "normal"},
    {"title": "Montar carrossel de resultados/depoimentos", "department": "MKT", "day_offset": 5, "priority": "alta"},
    {"title": "Abrir campanha de upsell (próxima turma / produto)", "department": "VND", "day_offset": 5, "priority": "alta"},
    {"title": "Fechar pagamentos pendentes a fornecedores", "department": "FIN", "day_offset": 7, "priority": "urgente"},
    {"title": "Conferir todos os recebimentos na plataforma", "department": "FIN", "day_offset": 7, "priority": "alta"},
    {"title": "Montar DRE final do evento", "department": "FIN", "day_offset": 10, "priority": "urgente"},
    {"title": "Calcular margem real e comparar com meta", "department": "FIN", "day_offset": 10, "priority": "alta"},
    {"title": "Reunião de retrospectiva com equipe", "department": "ADM", "day_offset": 10, "priority": "alta"},
    {"title": "Documentar aprendizados e melhorias para próxima edição", "department": "ADM", "day_offset": 12, "priority": "normal"},
    {"title": "Publicar aftermovie nas redes", "department": "MKT", "day_offset": 14, "priority": "normal"},
    {"title": "Sequência de email pós-evento (relacionamento + oferta)", "department": "MKT", "day_offset": 14, "priority": "alta"},
    {"title": "Enviar pesquisa de satisfação completa", "department": "ATD", "day_offset": 14, "priority": "normal"},
    {"title": "Atualizar CRM com status dos participantes", "department": "VND", "day_offset": 14, "priority": "normal"},
    {"title": "Analisar ROI de tráfego (custo por inscrição)", "department": "MKT", "day_offset": 15, "priority": "normal"},
    {"title": "Encerrar evento no sistema (status: encerrado)", "department": "ADM", "day_offset": 20, "priority": "normal"},
    {"title": "Arquivar contratos e notas fiscais", "department": "FIN", "day_offset": 20, "priority": "normal"},
    {"title": "Relatório final para sócios/stakeholders", "department": "ADM", "day_offset": 20, "priority": "alta"},
    {"title": "Iniciar planejamento da próxima edição", "department": "ADM", "day_offset": 30, "priority": "normal"}
  ]'::jsonb
);

-- ============================================================
-- TEMPLATE: CONGRESSO (ex: Nutrição Brasil)
-- 98 tarefas
-- ============================================================
INSERT INTO public.pop_templates (name, event_type, tasks) VALUES (
  'Congresso / Evento Científico (Nutrição Brasil)',
  'congresso',
  '[
    {"title": "Definir tema central e eixos temáticos", "department": "ADM", "day_offset": -150, "priority": "urgente"},
    {"title": "Definir data, cidade e venue", "department": "ADM", "day_offset": -150, "priority": "urgente"},
    {"title": "Assinar contrato com venue/centro de convenções", "department": "PROD", "day_offset": -140, "priority": "urgente"},
    {"title": "Definir grade de palestrantes (curadoria)", "department": "ADM", "day_offset": -130, "priority": "urgente"},
    {"title": "Enviar convites formais aos palestrantes", "department": "ADM", "day_offset": -125, "priority": "alta"},
    {"title": "Negociar cachês e fechar contratos", "department": "FIN", "day_offset": -120, "priority": "alta"},
    {"title": "Definir meta de receita e estrutura de lotes/ingressos", "department": "FIN", "day_offset": -120, "priority": "alta"},
    {"title": "Montar categorias de ingresso (standard, premium, VIP)", "department": "VND", "day_offset": -115, "priority": "alta"},
    {"title": "Criar identidade visual e KV do congresso", "department": "MKT", "day_offset": -120, "priority": "alta"},
    {"title": "Desenvolver site/LP do evento", "department": "MKT", "day_offset": -110, "priority": "urgente"},
    {"title": "Configurar plataforma de vendas (Sympla/Hotmart)", "department": "VND", "day_offset": -110, "priority": "alta"},
    {"title": "Montar deck de patrocínio/apoio", "department": "VND", "day_offset": -110, "priority": "alta"},
    {"title": "Prospectar patrocinadores (lista target)", "department": "VND", "day_offset": -105, "priority": "alta"},
    {"title": "Enviar propostas de patrocínio", "department": "VND", "day_offset": -100, "priority": "alta"},
    {"title": "Criar criativos para tráfego (estáticos + vídeo)", "department": "MKT", "day_offset": -100, "priority": "alta"},
    {"title": "Montar estratégia de tráfego pago", "department": "MKT", "day_offset": -100, "priority": "alta"},
    {"title": "Abrir vendas — Lote 1 (early bird)", "department": "VND", "day_offset": -95, "priority": "urgente"},
    {"title": "Iniciar campanhas de tráfego pago", "department": "MKT", "day_offset": -95, "priority": "urgente"},
    {"title": "Criar sequência de emails de lançamento", "department": "MKT", "day_offset": -95, "priority": "alta"},
    {"title": "Publicar anúncio nas redes sociais (palestrantes)", "department": "MKT", "day_offset": -90, "priority": "alta"},
    {"title": "Fechar primeiro bloco de patrocinadores", "department": "VND", "day_offset": -85, "priority": "alta"},
    {"title": "Confirmar programação/horários com palestrantes", "department": "PROD", "day_offset": -80, "priority": "alta"},
    {"title": "Definir layout do espaço (salas, auditório, stands)", "department": "PROD", "day_offset": -75, "priority": "alta"},
    {"title": "Orçar audiovisual (som, projeção, LED)", "department": "PROD", "day_offset": -75, "priority": "alta"},
    {"title": "Orçar decoração e cenografia", "department": "PROD", "day_offset": -70, "priority": "normal"},
    {"title": "Orçar alimentação/coffee break (grande porte)", "department": "PROD", "day_offset": -70, "priority": "alta"},
    {"title": "Virada de lote 1 → lote 2", "department": "VND", "day_offset": -65, "priority": "urgente"},
    {"title": "Campanha de virada de lote (email + tráfego)", "department": "MKT", "day_offset": -65, "priority": "urgente"},
    {"title": "Contratar empresa de audiovisual", "department": "PROD", "day_offset": -60, "priority": "alta"},
    {"title": "Contratar fotógrafo e videomaker", "department": "PROD", "day_offset": -60, "priority": "normal"},
    {"title": "Contratar equipe de credenciamento", "department": "PROD", "day_offset": -55, "priority": "normal"},
    {"title": "Produzir materiais gráficos (backdrop, banner, totens)", "department": "PROD", "day_offset": -50, "priority": "alta"},
    {"title": "Fechar bloco de passagens aéreas", "department": "FIN", "day_offset": -50, "priority": "alta"},
    {"title": "Reservar hospedagem (equipe + palestrantes)", "department": "PROD", "day_offset": -50, "priority": "alta"},
    {"title": "Segundo round de prospecção de patrocínio", "department": "VND", "day_offset": -50, "priority": "normal"},
    {"title": "Produzir conteúdo com palestrantes (reels, entrevistas)", "department": "MKT", "day_offset": -45, "priority": "alta"},
    {"title": "Virada de lote 2 → lote 3", "department": "VND", "day_offset": -35, "priority": "urgente"},
    {"title": "Campanha agressiva de vendas (últimas vagas)", "department": "MKT", "day_offset": -35, "priority": "urgente"},
    {"title": "Produzir crachás e credenciais", "department": "PROD", "day_offset": -30, "priority": "alta"},
    {"title": "Produzir sacolas/kits de boas-vindas", "department": "PROD", "day_offset": -30, "priority": "normal"},
    {"title": "Montar cronograma operacional (minuto a minuto)", "department": "PROD", "day_offset": -25, "priority": "urgente"},
    {"title": "Confirmar todos os fornecedores (checklist)", "department": "PROD", "day_offset": -20, "priority": "urgente"},
    {"title": "Enviar briefing final aos palestrantes", "department": "PROD", "day_offset": -20, "priority": "alta"},
    {"title": "Definir escalas da equipe (quem faz o quê no dia)", "department": "PROD", "day_offset": -15, "priority": "urgente"},
    {"title": "Enviar email logístico aos participantes", "department": "ATD", "day_offset": -14, "priority": "urgente"},
    {"title": "Publicar programação final no site", "department": "MKT", "day_offset": -14, "priority": "alta"},
    {"title": "Criar plano de conteúdo ao vivo (stories, live)", "department": "MKT", "day_offset": -10, "priority": "normal"},
    {"title": "DRE provisório — conferir receita vs custos", "department": "FIN", "day_offset": -10, "priority": "alta"},
    {"title": "Encerrar vendas online", "department": "VND", "day_offset": -5, "priority": "alta"},
    {"title": "Imprimir lista de check-in final", "department": "ATD", "day_offset": -5, "priority": "alta"},
    {"title": "Montar kits por participante", "department": "PROD", "day_offset": -3, "priority": "alta"},
    {"title": "Enviar lembrete final (WhatsApp + email)", "department": "ATD", "day_offset": -3, "priority": "alta"},
    {"title": "Visita técnica ao venue (montagem D-2)", "department": "PROD", "day_offset": -2, "priority": "urgente"},
    {"title": "Montagem completa do evento", "department": "PROD", "day_offset": -1, "priority": "urgente"},
    {"title": "Teste geral de som/projeção/iluminação", "department": "PROD", "day_offset": -1, "priority": "urgente"},
    {"title": "Reunião de alinhamento com toda equipe", "department": "ADM", "day_offset": -1, "priority": "urgente"},
    {"title": "Organizar credenciamento + sinalização", "department": "ATD", "day_offset": -1, "priority": "alta"},
    {"title": "Montagem de stands de patrocinadores", "department": "PROD", "day_offset": -1, "priority": "alta"},
    {"title": "DIA DO EVENTO: check-in e recepção", "department": "ATD", "day_offset": 0, "priority": "urgente"},
    {"title": "Acompanhar timeline operacional do dia", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Cobertura fotográfica e de vídeo completa", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Stories e conteúdo ao vivo", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Gestão de imprevistos em tempo real", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Coletar depoimentos em vídeo", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Aplicar pesquisa NPS/feedback ao final", "department": "ATD", "day_offset": 0, "priority": "alta"},
    {"title": "Coordenar desmontagem pós-evento", "department": "PROD", "day_offset": 0, "priority": "alta"},
    {"title": "Enviar agradecimento (email + WhatsApp) D+1", "department": "ATD", "day_offset": 1, "priority": "urgente"},
    {"title": "Postar conteúdo de encerramento", "department": "MKT", "day_offset": 1, "priority": "alta"},
    {"title": "Entregar certificados digitais", "department": "ATD", "day_offset": 2, "priority": "alta"},
    {"title": "Disponibilizar gravações/replays (se aplicável)", "department": "ATD", "day_offset": 3, "priority": "normal"},
    {"title": "Compilar feedback NPS + relatório", "department": "ATD", "day_offset": 5, "priority": "normal"},
    {"title": "Editar aftermovie / vídeo highlight", "department": "MKT", "day_offset": 7, "priority": "normal"},
    {"title": "Fechar pagamentos a fornecedores", "department": "FIN", "day_offset": 7, "priority": "urgente"},
    {"title": "Cobrar saldo de patrocinadores", "department": "FIN", "day_offset": 7, "priority": "alta"},
    {"title": "Conferir todos os recebimentos", "department": "FIN", "day_offset": 10, "priority": "alta"},
    {"title": "Montar DRE final do congresso", "department": "FIN", "day_offset": 12, "priority": "urgente"},
    {"title": "Calcular ROI de marketing (CAC)", "department": "MKT", "day_offset": 12, "priority": "normal"},
    {"title": "Reunião de retrospectiva com equipe", "department": "ADM", "day_offset": 14, "priority": "alta"},
    {"title": "Documentar melhorias para próxima edição", "department": "ADM", "day_offset": 14, "priority": "normal"},
    {"title": "Publicar aftermovie e conteúdos finais", "department": "MKT", "day_offset": 14, "priority": "normal"},
    {"title": "Sequência de email pós (upsell próxima edição)", "department": "MKT", "day_offset": 15, "priority": "alta"},
    {"title": "Enviar relatório para patrocinadores (entrega de valor)", "department": "VND", "day_offset": 15, "priority": "alta"},
    {"title": "Atualizar CRM dos participantes", "department": "VND", "day_offset": 15, "priority": "normal"},
    {"title": "Relatório final para sócios/stakeholders", "department": "ADM", "day_offset": 20, "priority": "alta"},
    {"title": "Arquivar contratos, NFs e documentos", "department": "FIN", "day_offset": 20, "priority": "normal"},
    {"title": "Encerrar evento no sistema", "department": "ADM", "day_offset": 25, "priority": "normal"},
    {"title": "Iniciar planejamento da próxima edição", "department": "ADM", "day_offset": 45, "priority": "normal"}
  ]'::jsonb
);

-- ============================================================
-- TEMPLATE: MENTORIA (ex: A Mesa, pequenos grupos)
-- 60 tarefas
-- ============================================================
INSERT INTO public.pop_templates (name, event_type, tasks) VALUES (
  'Mentoria / Mastermind (A Mesa)',
  'mentoria',
  '[
    {"title": "Definir formato (grupo, individual, híbrido)", "department": "ADM", "day_offset": -90, "priority": "urgente"},
    {"title": "Definir número de vagas e critérios de seleção", "department": "ADM", "day_offset": -90, "priority": "alta"},
    {"title": "Definir preço e forma de pagamento", "department": "FIN", "day_offset": -85, "priority": "alta"},
    {"title": "Definir calendário de encontros (datas)", "department": "ADM", "day_offset": -80, "priority": "urgente"},
    {"title": "Reservar espaço para encontros presenciais", "department": "PROD", "day_offset": -75, "priority": "alta"},
    {"title": "Criar página de vendas exclusiva", "department": "MKT", "day_offset": -70, "priority": "alta"},
    {"title": "Montar narrativa de posicionamento premium", "department": "MKT", "day_offset": -70, "priority": "alta"},
    {"title": "Produzir vídeo de apresentação (VSL)", "department": "MKT", "day_offset": -65, "priority": "alta"},
    {"title": "Criar lista de convidados/prospects qualificados", "department": "VND", "day_offset": -65, "priority": "urgente"},
    {"title": "Enviar convites personalizados (email + WhatsApp)", "department": "VND", "day_offset": -60, "priority": "urgente"},
    {"title": "Follow-up com interessados (calls de qualificação)", "department": "VND", "day_offset": -55, "priority": "alta"},
    {"title": "Abrir inscrições para público geral (se aplicável)", "department": "VND", "day_offset": -50, "priority": "alta"},
    {"title": "Campanha de tráfego para LP da mentoria", "department": "MKT", "day_offset": -50, "priority": "alta"},
    {"title": "Stories de bastidores e expectativa", "department": "MKT", "day_offset": -45, "priority": "normal"},
    {"title": "Fechar grupo de mentorados (confirmar vagas)", "department": "VND", "day_offset": -30, "priority": "urgente"},
    {"title": "Enviar contrato/termos para mentorados", "department": "ADM", "day_offset": -28, "priority": "alta"},
    {"title": "Enviar formulário de onboarding (diagnóstico)", "department": "ATD", "day_offset": -25, "priority": "alta"},
    {"title": "Analisar formulários e preparar plano individual", "department": "ADM", "day_offset": -20, "priority": "alta"},
    {"title": "Criar grupo exclusivo (WhatsApp/Telegram)", "department": "ATD", "day_offset": -20, "priority": "alta"},
    {"title": "Enviar boas-vindas + cronograma aos participantes", "department": "ATD", "day_offset": -14, "priority": "alta"},
    {"title": "Preparar material do primeiro encontro", "department": "PROD", "day_offset": -10, "priority": "alta"},
    {"title": "Confirmar logística do encontro presencial", "department": "PROD", "day_offset": -7, "priority": "alta"},
    {"title": "Enviar lembrete do primeiro encontro", "department": "ATD", "day_offset": -3, "priority": "alta"},
    {"title": "ENCONTRO 1: Realizar e registrar insights", "department": "ADM", "day_offset": 0, "priority": "urgente"},
    {"title": "Enviar resumo/ata do encontro ao grupo", "department": "ATD", "day_offset": 1, "priority": "alta"},
    {"title": "Definir tarefas/desafios entre encontros", "department": "ADM", "day_offset": 1, "priority": "alta"},
    {"title": "Follow-up individual (check se está aplicando)", "department": "ATD", "day_offset": 7, "priority": "normal"},
    {"title": "Preparar material do encontro 2", "department": "PROD", "day_offset": 10, "priority": "alta"},
    {"title": "Acompanhar evolução dos mentorados", "department": "ATD", "day_offset": 14, "priority": "normal"},
    {"title": "Coletar feedback parcial do grupo", "department": "ATD", "day_offset": 30, "priority": "normal"},
    {"title": "Ajustar conteúdo com base no feedback", "department": "ADM", "day_offset": 32, "priority": "normal"},
    {"title": "Planejar experiência de encerramento", "department": "PROD", "day_offset": 45, "priority": "alta"},
    {"title": "Preparar certificado/entregável final", "department": "PROD", "day_offset": 50, "priority": "normal"},
    {"title": "Coletar depoimentos em vídeo dos mentorados", "department": "MKT", "day_offset": 55, "priority": "alta"},
    {"title": "Realizar encontro de encerramento", "department": "ADM", "day_offset": 60, "priority": "urgente"},
    {"title": "Enviar pesquisa NPS final", "department": "ATD", "day_offset": 62, "priority": "alta"},
    {"title": "Propor continuidade/upgrade (próxima fase)", "department": "VND", "day_offset": 62, "priority": "alta"},
    {"title": "Montar DRE final da mentoria", "department": "FIN", "day_offset": 65, "priority": "alta"},
    {"title": "Documentar cases de sucesso para marketing", "department": "MKT", "day_offset": 65, "priority": "alta"},
    {"title": "Reunião de retrospectiva interna", "department": "ADM", "day_offset": 70, "priority": "normal"}
  ]'::jsonb
);

-- ============================================================
-- TEMPLATE: WORKSHOP (1 dia, hands-on)
-- 55 tarefas
-- ============================================================
INSERT INTO public.pop_templates (name, event_type, tasks) VALUES (
  'Workshop Presencial (1 dia)',
  'workshop',
  '[
    {"title": "Definir tema e público-alvo específico", "department": "ADM", "day_offset": -60, "priority": "urgente"},
    {"title": "Definir data, cidade e local", "department": "ADM", "day_offset": -60, "priority": "urgente"},
    {"title": "Reservar espaço (sala, auditório)", "department": "PROD", "day_offset": -55, "priority": "alta"},
    {"title": "Definir preço e limite de vagas", "department": "FIN", "day_offset": -50, "priority": "alta"},
    {"title": "Criar página de vendas", "department": "MKT", "day_offset": -45, "priority": "urgente"},
    {"title": "Configurar plataforma de pagamento", "department": "VND", "day_offset": -45, "priority": "alta"},
    {"title": "Produzir criativos para tráfego", "department": "MKT", "day_offset": -40, "priority": "alta"},
    {"title": "Iniciar tráfego pago", "department": "MKT", "day_offset": -38, "priority": "urgente"},
    {"title": "Sequência de emails de abertura", "department": "MKT", "day_offset": -38, "priority": "alta"},
    {"title": "Posts orgânicos de divulgação", "department": "MKT", "day_offset": -35, "priority": "normal"},
    {"title": "Virada de lote (se aplicável)", "department": "VND", "day_offset": -25, "priority": "alta"},
    {"title": "Campanha de urgência", "department": "MKT", "day_offset": -25, "priority": "alta"},
    {"title": "Orçar coffee break/alimentação", "department": "PROD", "day_offset": -30, "priority": "normal"},
    {"title": "Preparar material didático/apostila", "department": "PROD", "day_offset": -20, "priority": "alta"},
    {"title": "Preparar slides/apresentação", "department": "PROD", "day_offset": -15, "priority": "alta"},
    {"title": "Contratar fotógrafo (se aplicável)", "department": "PROD", "day_offset": -15, "priority": "normal"},
    {"title": "Fechar vendas / últimas vagas", "department": "VND", "day_offset": -7, "priority": "alta"},
    {"title": "Enviar email logístico aos inscritos", "department": "ATD", "day_offset": -7, "priority": "urgente"},
    {"title": "Confirmar coffee break e fornecedores", "department": "PROD", "day_offset": -5, "priority": "alta"},
    {"title": "Imprimir materiais e crachás", "department": "PROD", "day_offset": -3, "priority": "alta"},
    {"title": "Enviar lembrete (WhatsApp + email)", "department": "ATD", "day_offset": -2, "priority": "alta"},
    {"title": "Preparar espaço e testar equipamentos", "department": "PROD", "day_offset": -1, "priority": "urgente"},
    {"title": "DIA DO WORKSHOP: check-in", "department": "ATD", "day_offset": 0, "priority": "urgente"},
    {"title": "Executar workshop conforme timeline", "department": "PROD", "day_offset": 0, "priority": "urgente"},
    {"title": "Registrar fotos e vídeos", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Coletar depoimentos", "department": "MKT", "day_offset": 0, "priority": "alta"},
    {"title": "Aplicar NPS ao final", "department": "ATD", "day_offset": 0, "priority": "alta"},
    {"title": "Enviar agradecimento D+1", "department": "ATD", "day_offset": 1, "priority": "urgente"},
    {"title": "Entregar material/gravação prometida", "department": "ATD", "day_offset": 2, "priority": "alta"},
    {"title": "Enviar certificado", "department": "ATD", "day_offset": 3, "priority": "normal"},
    {"title": "Postar conteúdo pós-evento", "department": "MKT", "day_offset": 3, "priority": "alta"},
    {"title": "Oferta de upsell (curso, mentoria, próximo)", "department": "VND", "day_offset": 3, "priority": "alta"},
    {"title": "Fechar pagamentos a fornecedores", "department": "FIN", "day_offset": 5, "priority": "alta"},
    {"title": "Montar DRE do workshop", "department": "FIN", "day_offset": 7, "priority": "alta"},
    {"title": "Documentar aprendizados", "department": "ADM", "day_offset": 7, "priority": "normal"}
  ]'::jsonb
);

-- ============================================================
-- TEMPLATE: MASTERCLASS (online ou híbrido, sessão única)
-- 40 tarefas
-- ============================================================
INSERT INTO public.pop_templates (name, event_type, tasks) VALUES (
  'Masterclass (Online/Híbrida)',
  'masterclass',
  '[
    {"title": "Definir tema e palestrante", "department": "ADM", "day_offset": -45, "priority": "urgente"},
    {"title": "Definir data e formato (online/presencial/híbrido)", "department": "ADM", "day_offset": -45, "priority": "urgente"},
    {"title": "Definir se é gratuita ou paga", "department": "FIN", "day_offset": -40, "priority": "alta"},
    {"title": "Criar LP de inscrição", "department": "MKT", "day_offset": -35, "priority": "urgente"},
    {"title": "Configurar plataforma de transmissão (Zoom/YouTube)", "department": "PROD", "day_offset": -35, "priority": "alta"},
    {"title": "Produzir criativos de divulgação", "department": "MKT", "day_offset": -30, "priority": "alta"},
    {"title": "Iniciar tráfego pago para inscrições", "department": "MKT", "day_offset": -28, "priority": "urgente"},
    {"title": "Email de lançamento para base", "department": "MKT", "day_offset": -28, "priority": "alta"},
    {"title": "Campanha orgânica (stories, reels)", "department": "MKT", "day_offset": -25, "priority": "normal"},
    {"title": "Preparar slides da masterclass", "department": "PROD", "day_offset": -15, "priority": "alta"},
    {"title": "Definir oferta/CTA do final (se gratuita com upsell)", "department": "VND", "day_offset": -15, "priority": "alta"},
    {"title": "Testar link de transmissão e equipamentos", "department": "PROD", "day_offset": -7, "priority": "alta"},
    {"title": "Enviar lembrete aos inscritos (D-3)", "department": "ATD", "day_offset": -3, "priority": "alta"},
    {"title": "Enviar lembrete dia anterior", "department": "ATD", "day_offset": -1, "priority": "alta"},
    {"title": "Enviar lembrete 1h antes (WhatsApp)", "department": "ATD", "day_offset": 0, "priority": "urgente"},
    {"title": "REALIZAR MASTERCLASS", "department": "ADM", "day_offset": 0, "priority": "urgente"},
    {"title": "Abrir chat/interação com participantes", "department": "ATD", "day_offset": 0, "priority": "alta"},
    {"title": "Apresentar oferta/CTA no final", "department": "VND", "day_offset": 0, "priority": "urgente"},
    {"title": "Enviar replay + link da oferta (D+1)", "department": "ATD", "day_offset": 1, "priority": "urgente"},
    {"title": "Sequência de emails pós-masterclass", "department": "MKT", "day_offset": 1, "priority": "alta"},
    {"title": "Campanha de urgência da oferta (48h)", "department": "MKT", "day_offset": 2, "priority": "alta"},
    {"title": "Encerrar oferta especial", "department": "VND", "day_offset": 4, "priority": "alta"},
    {"title": "Analisar métricas (inscritos, presentes, conversão)", "department": "MKT", "day_offset": 5, "priority": "alta"},
    {"title": "Montar DRE da masterclass", "department": "FIN", "day_offset": 5, "priority": "normal"},
    {"title": "Documentar o que funcionou", "department": "ADM", "day_offset": 7, "priority": "normal"}
  ]'::jsonb
);
